version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
            

      - run:
          name: Build project
          command: |
            # Add build commands here
            echo "Build command 1"
            echo "Build command 2"
            # ...

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
