version: 2.1

machine:

  pre:
    - bash ./test_circle_bash.sh

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip

      - run:
          name: Build and Package
          command: |
            # Install dependencies
            pip install -r requirements.txt

            # Create the artifacts directory if it doesn't exist
            mkdir -p artifacts

            # Move to the root directory
            cd ~/repo

            # Run the custom build script
            ./build.sh

            # Move the generated artifacts to the artifacts directory
            mv <path_to_artifacts>/* artifacts/

      - persist_to_workspace:
          root: .
          paths:
            - artifacts/

workflows:
  version: 2
  build_workflow:
    jobs:
      - build

