version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip

      - run:
          name: Build and Package
          command: |
            # Install dependencies
            pip install -r requirements.txt

            # Create the artifacts directory if it doesn't exist
            mkdir -p artifacts

            # Move to the root directory
            cd ~/repo

            # Check if the required file exists
            if [ ! -f "file.txt" ]; then
              echo "File.txt is missing. Aborting the build."
              exit 1
            fi

            # Move the generated artifacts to the artifacts directory
            mv dist/* artifacts/

      - persist_to_workspace:
          root: .
          paths:
            - artifacts/

workflows:
  version: 2
  build_workflow:
    jobs:
      - build

