version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip

      - run:
          name: Build and Package
          command: |
            # Build your Python package
            python setup.py sdist bdist_wheel

            # Create a directory to store the artifacts
            mkdir -p artifacts

            # Move the generated package artifacts to the artifacts directory
            mv dist/* artifacts/

      - persist_to_workspace:
          root: .
          paths:
            - artifacts/

  publish:
    docker:
      - image: circleci/python:3.8

    steps:
      - attach_workspace:
          at: .

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t karthik4544/fastapi:latest .
            docker push karthik4544/fastapi:latest

      - store_artifacts:
          path: artifacts

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
      - publish
      
      
