version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip

      - run:
          name: Build and Package
          command: |
            # Install dependencies
            pip install -r requirements.txt

            # Build your Python package
            python setup.py sdist bdist_wheel

            # Create the artifacts directory if it doesn't exist
            mkdir -p artifacts

            # Move the generated package artifacts to the artifacts directory
            mv dist/* artifacts/

      - persist_to_workspace:
          root: .
          paths:
            - artifacts/

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
